export const TYPES = {
  APP: {
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
  },
  POSTS: {
    LOAD_ALL_POSTS: 'LOAD_ALL_POSTS',
    LOAD_BOOKED_POSTS: 'LOAD_BOOKED_POSTS',
  }
}
