export const TYPES = {
  APP: {
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
  },
  POSTS: {
    LOAD_ALL_POSTS: 'LOAD_ALL_POSTS',
    TOGGLE_BOOKED: 'TOGGLE_BOOKED',
    REMOVE_POST: 'REMOVE_POST',
  }
}
